config/routes.rb
ApiLawnMowingApp::Application.routes.draw do
  resources :lawns do 
    member do 
      post '/:id/execute' => 'lawn#execute', as: :execute
    end
    resources :mowers
  end

  get '/lawn/:id/execute', controller: 'lawns', action: "execute", as: :lawn_execute
  match '/',        to: 'lawns#index',    via: 'get'
  match '/home',    to: 'lawns#index',    via: 'get'

end

app/models/lawn.rb
class Lawn < ActiveRecord::Base
	has_many :mowers

  validates_presence_of :width, :height
  validates :width, numericality: { only_integer: true }
  validates :height, numericality: { only_integer: true }

  def to_s
  	return "id:#{id} width:#{width} height:#{height} mower count:#{mowers.count}"
  end

  def array_positions 
  	array = []
  	array << "#{self.width} #{self.height}"
  	mowers.each_with_index do |mower, index|
  		array << "#{mower.x} #{mower.y} #{mower.headings}"
  		array << "#{mower.commands}"
  	end
  	array
  end

  def set_mowers_values(lawn_mowers_positions)
  	puts "\n\n\n\n-------- #{lawn_mowers_positions}  #{lawn_mowers_positions.count}-----"
  	mowers.each_with_index do |mower, index|
  		array = lawn_mowers_positions[index + 1]
  		puts "array:#{array}"
  		x = array[0]
  		y = array[1]
  		headings = array[2]
  		commands = array[3]

  		mower.update_attributes(x: x, y: y, headings: headings, commands: commands)
  	end
  end
end

app/models/mower.rb
class Mower < ActiveRecord::Base
  belongs_to :lawn, dependent: :destroy

  validates_presence_of :x, :y, :headings, :commands
  validates :x, numericality: { only_integer: true }
  validates :y, numericality: { only_integer: true }

  validate :all_validations
  def all_validations
  	unless headings.nil? || /^(N|S|E|W)$/.match(headings) 
  		errors.add(:headings, "Headings is invalid.  It should be S, E, N or W")
  	end
  	unless commands.nil? || /^[LRM]*$/.match(commands)
  		errors.add(:commands, "Commands is invalid.  It should be M, L or R")
  	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lawns_controller.rb
require 'lawn_mowing'
# require "#{Rails.root}/vendor/plugins/lawn_mowing/lawn_mowing.rb"


class LawnsController < ApplicationController
  before_action :set_lawn, only: [:show, :edit, :update, :destroy, :execute]

  # GET /lawns
  # GET /lawns.json
  def index
    @lawns = Lawn.all
  end

  # GET /lawns/1
  # GET /lawns/1.json
  def show
  end

  # GET /lawns/new
  def new
    @lawn = Lawn.new
  end

  # GET /lawns/1/edit
  def edit
  end

  # POST /lawns
  # POST /lawns.json
  def create
    @lawn = Lawn.new(lawn_params)

    respond_to do |format|
      if @lawn.save
        format.html { redirect_to @lawn, notice: 'Lawn was successfully created.' }
        # format.json { render :show, status: :created, location: @lawn }
        # j = { json: {width: @lawn.width, height: @lawn.height, id: @lawn.id } }
        # puts "\n\n\njjjj:#{j}"
        # format.json j { render status: : creates, j}

        format.json { render json: @lawn }
      else
        format.html { render :new }
        # render :json => {'error' => 'authentication error'}, :status => 401
        format.json { render json: @lawn.errors, status: :unprocessable_entity }

      end
    end
  end

  # PATCH/PUT /lawns/1
  # PATCH/PUT /lawns/1.json
  def update
    respond_to do |format|
      if @lawn.update(lawn_params)
        format.html { redirect_to @lawn, notice: 'Lawn was successfully updated.' }
        format.json { render :show, status: :ok, location: @lawn }
      else
        format.html { render :edit }
        format.json { render json: @lawn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lawns/1
  # DELETE /lawns/1.json
  def destroy
    @lawn.destroy
    respond_to do |format|
      format.html { redirect_to lawns_url, notice: 'Lawn was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def execute
    array_list = @lawn.array_positions
    mowing_system = LawnMowing::MowingSystem.init_run_system(array_list)
    @lawn.set_mowers_values(mowing_system.lawn_mowers_positions)
    @lawn.save

    respond_to do |format|
      format.html { redirect_to @lawn, notice: 'Mowing system was run.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lawn
      @lawn = Lawn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lawn_params
      params.require(:lawn).permit(:width, :height)
    end
end

app/controllers/mowers_controller.rb
class MowersController < ApplicationController
  before_action :set_mower, only: [:show, :edit, :update, :destroy]
  before_action :set_lawn, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  

  # GET /mowers
  # GET /mowers.json
  def index
    @mowers = Mower.all || []
  end

  # GET /mowers/1
  # GET /mowers/1.json
  def show
  end

  # GET /lawns/lawn_id/mowers/new
  def new
    @mower = Mower.new
  end

  # GET /mowers/1/edit
  def edit
  end

  # POST /mowers
  # POST /mowers.json
  def create
    respond_to do |format|
      @mower = @lawn.mowers.create(mower_params)
      if @mower.errors.empty?
        format.html { redirect_to edit_lawn_mower_path(id_lawn: @lawn.id, id: @mower.id), notice: 'Mower was successfully created.' }
        format.json { render :show, status: :created, location: @mower }
      else
        format.html { render :new }
        format.json { render json: @mower.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mowers/1
  # PATCH/PUT /mowers/1.json
  def update
    respond_to do |format|
      if @mower.update(mower_params)
        # format.html { redirect_to edit_lawn_mower_path(id_lawn: @lawn.id, id: @mower.id), notice: 'Mower was successfully updated.' }
        format.html { redirect_to lawn_mower_path(id_lawn: @lawn.id, id: @mower.id), notice: 'Mower was successfully updated.' }
        format.json { render :show, status: :ok, location: @mower }
      else
        format.html { render :edit }
        format.json { render json: @mower.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mowers/1
  # DELETE /mowers/1.json
  def destroy
    @mower.destroy
    respond_to do |format|
      format.html { redirect_to lawn_mowers_path(lawn_id: @lawn.id), notice: 'Mower was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mower
      @mower = Mower.find(params[:id])
    end

    def set_lawn
      @lawn = Lawn.find params[:lawn_id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mower_params
      params.require(:mower).permit(:x, :y, :headings, :commands)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lawns_helper.rb
module LawnsHelper
end

app/helpers/mowers_helper.rb
module MowersHelper
end

app/views/lawns/_form.html.erb
<%= form_for(@lawn) do |f| %>
  <% if @lawn.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lawn.errors.count, "error") %> prohibited this lawn from being saved:</h2>

      <ul>
      <% @lawn.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :width %><br>
    <%= f.number_field :width %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.number_field :height %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lawns/edit.html.erb
<h1>Editing Lawn</h1>

<%= render 'form' %>

<%= link_to 'Show', @lawn %> |
<%= link_to 'Back', lawns_path %>

app/views/lawns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lawns</h1>

<table>
  <thead>
    <tr>
      <th>Width</th>
      <th>Height</th>
      <th colspan="5">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% unless @lawns %>
      <p><h3>No Lawn.  Please create the first.</h3></p>
    <% else %>
      <% @lawns.each do |lawn| %>
        <tr>
          <td><%= lawn.width %></td>
          <td><%= lawn.height %></td>
          <td><%= link_to 'Show', lawn %></td>
          <td><%= link_to 'Edit', edit_lawn_path(lawn) %></td>
          <td><%= link_to 'Destroy', lawn, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><%= link_to 'Add Mower', new_lawn_mower_path(lawn_id: lawn.id) %></td>
          <td><%= link_to 'List Mowers', lawn_mowers_path(lawn_id: lawn.id) %></td>
          <td><%= link_to 'Execute Lawn Mowing', lawn_execute_path(id: lawn.id) %></td>          
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lawn', new_lawn_path %>

app/views/lawns/new.html.erb
<h1>New Lawn</h1>

<%= render 'form' %>

<%= link_to 'Back', lawns_path %>

app/views/lawns/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Information of Lawn <%= @lawn.id %>
<p>
  <strong>Width:</strong>
  <%= @lawn.width %>
</p>

<p>
  <strong>Height:</strong>
  <%= @lawn.height %>
</p>

<p>
	<td><%= link_to 'Execute Lawn Mowing', lawn_execute_path(id: @lawn.id) %></td>
</p>

<%= render :partial => "mowers/list_mowers", locals: {mowers: @lawn.mowers } %>

<%= link_to 'Edit', edit_lawn_path(@lawn) %> |
<%= link_to 'Back', lawns_path %>
<td><%= link_to 'Add Mower', new_lawn_mower_path(lawn_id: @lawn.id) %></td>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApiLawnMowing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mowers/_form.html.erb
<%= form_for(@mower, as: :mower,  url: (@mower.new_record? ? lawn_mowers_path(lawn_id: @lawn.id) : lawn_mower_path(lawn_id: @lawn.id, id: @mower.id) )) do |f| %>

<%#= simple_form_for @contact, url: (@contact.new_record? ? contacts_path : contact_path), html: {multipart: true}  do |f| %>

  <% if @mower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mower.errors.count, "error") %> prohibited this mower from being saved:</h2>

      <ul>
      <% @mower.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :x %><br>
    <%= f.number_field :x %>
  </div>
  <div class="field">
    <%= f.label :y %><br>
    <%= f.number_field :y %>
  </div>
  <div class="field">
    <%= f.label :headings %><br>
    <%= f.text_field :headings %>
  </div>
  <div class="field">
    <%= f.label :commands %><br>
    <%= f.text_field :commands %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mowers/_list_mowers.html.erb
<table>
  <thead>
    <tr>
      <th>X</th>
      <th>Y</th>
      <th>Headings</th>
      <th>Commands</th>
      <th>Lawn</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% mowers.each do |mower| %>
      <tr>
        <td><%= mower.x %></td>
        <td><%= mower.y %></td>
        <td><%= mower.headings %></td>
        <td><%= mower.commands %></td>
        <td><%= mower.lawn %></td>
        <td><%= link_to 'Show', lawn_mower_path(lawn_id: mower.lawn.id, id: mower.id) %></td>
        <td><%= link_to 'Edit', edit_lawn_mower_path(lawn_id: mower.lawn.id, id:mower.id) %></td>
        <td><%= link_to 'Destroy', lawn_mower_path(lawn_id: mower.lawn.id, id:mower.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Show Lawn', mower.lawn %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/mowers/edit.html.erb
<h1>Editing Mower</h1>

<%= render 'form' %>

<%= link_to 'Show', lawn_mower_path(lawn_id: @lawn, id: @mower) %> |
<%= link_to 'Back', lawn_mowers_path %>

app/views/mowers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Mowers</h1>

<%= render :partial => "mowers/list_mowers", locals: {mowers: @mowers } %>

<br>

<%= link_to 'New Mower', new_lawn_mower_path(lawn_id: @lawn.id) %>

app/views/mowers/new.html.erb
<h1>New Mower</h1>

<%= render 'form' %>

<%= link_to 'Back', lawn_mowers_path %>

app/views/mowers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>X:</strong>
  <%= @mower.x %>
</p>

<p>
  <strong>Y:</strong>
  <%= @mower.y %>
</p>

<p>
  <strong>Headings:</strong>
  <%= @mower.headings %>
</p>

<p>
  <strong>Commands:</strong>
  <%= @mower.commands %>
</p>

<p>
  <strong>Lawn:</strong>
  <%= @mower.lawn %>
</p>

<%= link_to 'Edit', edit_lawn_mower_path(lawn_id: @lawn.id, id:@mower.id) %> |
<%= link_to 'Back', lawn_mowers_path %>